#!/usr/bin/env bash
# Configure_your_Nginx server_to have_a custom_404 page_that contains_the_string

sudo apt-get update
sudo apt-get install -y nginx

# code_to_redirect a_specific_endpoint (eg: redirect_/redirect_me to_https://blog.ehoneahobed.com)
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code_to create_error page_and add a redirect_for error_404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart_the_server
sudo service nginx restart
