#! usr/bin/env bash
# Automating_nginx_configuration

sudo apt-get update
sudo apt-get -y install nginx

# adding_the_custom_header
sudo sed -i "https {/a\       add_header X-Served-By $HOSTNAME;"  /etc/nginx/nginx/conf

sudo service nginx restart
