#!/usr/bin/env bash
# This_bash script_generates file /var/run/myscript.pid contains its_PID
# printout To_infinity & beyond_indefinite
# Show I_hate the_kill_command when_receiving a SIGTERM_signal
# printout YU no love me?! when_receiving SIGINT_signal
# Delete the_file /var/run/myscript.pid & terminate itself when_receiving a SIGQUIT or SIGTERM_signal

echo $BASHPID > /var/run/myscript.pid
i=1
while ((i < 8))
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
	sleep 2
done
