#!/usr/bin/env bash
# This Bash_script accepts one_argument, which should_be a username.
# Runs the 'whoami' command under_the user_passed as an_argument.

# Use 'sudo' to_run 'whoami' as the_specified_user
sudo -u "$1" whoami
